---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: 3e16a2ade70e6ff2d339d2e3953ef561e64c2993
    app.quarkus.io/build-timestamp: 2021-12-06 - 20:03:12 +0000
  labels:
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/name: idaas-operator
  name: idaas-operator
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 3e16a2ade70e6ff2d339d2e3953ef561e64c2993
    app.quarkus.io/build-timestamp: 2021-12-06 - 20:03:12 +0000
  labels:
    app.kubernetes.io/name: idaas-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: idaas-operator
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: idaas-operator
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: idaas-operator-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: idaas-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 3e16a2ade70e6ff2d339d2e3953ef561e64c2993
    app.quarkus.io/build-timestamp: 2021-12-06 - 20:03:12 +0000
  labels:
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.kubernetes.io/name: idaas-operator
  name: idaas-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
      app.kubernetes.io/name: idaas-operator
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 3e16a2ade70e6ff2d339d2e3953ef561e64c2993
        app.quarkus.io/build-timestamp: 2021-12-06 - 20:03:12 +0000
      labels:
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
        app.kubernetes.io/name: idaas-operator
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: psmalan/idaas-operator:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: idaas-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccount: idaas-operator
